export interface Ranking {
    posicion: number,
    piloto: String,
    total: number,
    tc: number,
    stc2000: number,
    tn3: number,
    trv6: number,
    tnc2: number,
    tcp: number,
    tc2000: number,
    tcpk: number,
    tcm: number,
    tcpm: number,
    tpc3: number,
    trs: number,
    tpc2: number,
    trj: number,
    tpc1: number,
    pca: number,
    pcb: number,
    ptsAnt: number,
    ptsAct: number
}
